### ISSUE TITLE
Getting load error when requiring lib/somefile

### ISSUE THREAD

**Issue by jmcaffee** [iconara/puck#12]
I'm getting a load error when requiring my `lib/somefile`.
I'm not sure if I'm missing something or doing something wrong.

**System specs:**
  OS:
    Ubuntu 14.04 x64
    3.13.0-27-generic

  Java:
    java version "1.7.0_76"
    Java(TM) SE Runtime Environment (build 1.7.0_76-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 24.76-b04, mixed mode)

  rbenv:
    rbenv 0.4.0-129-g7e0e85b

  jruby:
    jruby 1.7.18 (1.9.3p551) 2014-12-22 625381c on Java HotSpot(TM) 64-Bit Server VM 1.7.0_76-b13 +jit [linux-amd64]

**Background:**
  I'm creating a jruby app on ubuntu and running it on Windows 7.
  When I run the app, the lib require (in `bin/mytestapp`) fails with

    LoadError: no such file to load -- mytestapp

This happens on both Java 7 and 8 runtimes.

I'm using the following require statement in `bin/mytestapp`

```ruby
    begin
      require 'mytestapp'
    rescue LoadError
      $LOAD_PATH.unshift File.expand_path("../../lib", __FILE__)
      puts 'LOAD_PATH:'
      $LOAD_PATH.each do |p|
        puts "  #{p}"
      end
      require 'mytestapp'
    end
```

I run the app on the build machine (linux) with

    java -jar build/mytestapp.jar mytestapp

I see the following output:

    LOAD_PATH:
      classpath:/META-INF/app.home/lib
      file:/home/jeff/projects/ruby/mytestapp/build/mytestapp.jar!/META-INF/jruby.home/lib/ruby/1.9/site_ruby
      file:/home/jeff/projects/ruby/mytestapp/build/mytestapp.jar!/META-INF/jruby.home/lib/ruby/shared
      file:/home/jeff/projects/ruby/mytestapp/build/mytestapp.jar!/META-INF/jruby.home/lib/ruby/1.9
      classpath:META-INF/gem.home/rake-10.1.0/lib
      classpath:META-INF/gem.home/builder-3.2.2/lib
      classpath:META-INF/gem.home/dbd-jdbc-0.1.6-java/lib
      classpath:META-INF/gem.home/deprecated-2.0.1/lib
      ...
      classpath:META-INF/gem.home/xml-simple-1.1.2/lib
      classpath:META-INF/gem.home/user-choices-1.1.6.1/lib

The app runs as expected (no errors) but note the first listing:

    classpath:/META-INF/app.home/lib

compared to the first `gem.home` listing:

    classpath:META-INF/gem.home/rake-10.1.0/lib

the `gem.home` listing doesn't contain a leading slash.

When I run the app on windows, I see the following:

    C:\Apps\MyTestApp>java -jar mytestapp.jar mytestapp
    LOAD_PATH:
      classpath:C:/META-INF/app.home/lib
      file:/C:/Apps/MyTestApp/mytestapp.jar!/META-INF/jruby.home/lib/ruby/1.9/site_ruby
      file:/C:/Apps/MyTestApp/mytestapp.jar!/META-INF/jruby.home/lib/ruby/shared
      file:/C:/Apps/MyTestApp/mytestapp.jar!/META-INF/jruby.home/lib/ruby/1.9
      classpath:META-INF/gem.home/rake-10.1.0/lib
      classpath:META-INF/gem.home/builder-3.2.2/lib
      classpath:META-INF/gem.home/dbd-jdbc-0.1.6-java/lib
      classpath:META-INF/gem.home/deprecated-2.0.1/lib
      ...
      classpath:META-INF/gem.home/xml-simple-1.1.2/lib
      classpath:META-INF/gem.home/user-choices-1.1.6.1/lib
    LoadError: no such file to load -- mytestapp
      require at org/jruby/RubyKernel.java:1071
      require at /C:/Apps/MyTestApp/mytestapp.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
      (root) at classpath:/META-INF/app.home/bin/mytestapp:20
        load at org/jruby/RubyKernel.java:1087
      (root) at classpath:jar-bootstrap.rb:50
        each at org/jruby/RubyArray.java:1613
      (root) at classpath:jar-bootstrap.rb:46

Now the `app.home` path is prefixed with `C:/`:

    classpath:C:/META-INF/app.home/lib

and it fails, as you can see.

**Question:** Why is the classpath prefixed with a file path? Shouldn't it just
be `META-INF/whatever`?

During my testing, I modified `puck/lib/puck/jar.rb#create_jar_bootstrap!` to
add the `lib` dir to the `LOAD_PATH` (line 148):

```ruby
    def create_jar_bootstrap!(tmp_dir, gem_dependencies)
      File.open(File.join(tmp_dir, 'jar-bootstrap.rb'), 'w') do |io|
        io.puts(%(PUCK_BIN_PATH = ['/#{JAR_APP_HOME}/bin', '/#{JAR_JRUBY_HOME}/bin']))
        gem_dependencies.each do |spec|
          io.puts("PUCK_BIN_PATH << '/#{JAR_GEM_HOME}/#{spec[:versioned_name]}/#{spec[:bin_path]}'")
        end
        io.puts

        #
        # Add JAR_APP_HOME/lib to LOAD_PATH
        #
        io.puts(%($LOAD_PATH << 'classpath:#{JAR_APP_HOME}/lib'))

        gem_dependencies.each do |spec|
          spec[:load_paths].each do |load_path|
            io.puts(%($LOAD_PATH << 'classpath:#{JAR_GEM_HOME}/#{spec[:versioned_name]}/#{load_path}'))
          end
        end
        io.puts
        io.puts(File.read(File.expand_path('../bootstrap.rb', __FILE__)))
      end
    end
```

My app now works in both systems, and I don't have to add the `lib` dir to the
`LOAD_PATH` in `bin/mytestapp`. I can just do:

    require 'mytestapp'

**Question:** Is there a reason to NOT add the `lib` dir to the `LOAD_PATH` within `create_jar_bootstrap`?
Will bad things happen?

**Question:** Maybe it would be better to make this a configuration option?

If I'm just losing it, please point me in the right direction.

Other than this issue, puck is working out great!

**Comment by iconara** [comment]
Thank you for the bug report, I very much appreciate the work you put into making it detailed and throrough.

Would it be correct to sum up the problem like this: the "standard" way of adding `lib` to the load path from a file in `bin` is by adding `File.expand_path('../../lib', __FILE__)`. When an application is packaged with Puck this works on *nix systems, but fails on Windows. The problem in Windows seems to be that the path is prepended with `C:/` to become `classpath:C:/META-INF/app.home/lib`.

> Question: Is there a reason to NOT add the lib dir to the LOAD_PATH within create_jar_bootstrap?
Will bad things happen?

Not sure.

Since Puck requires you to have a `lib` directory (it will error while creating the jar if there is no `lib` directory, see #10), it wouldn't be unreasonable to add it to the load path.

On the other hand, I want Puck to do as little as possible to make running from inside the jar different from running your code directly in its unpacked state.

In the unpacked state Ruby doesn't automatically put `lib` on the load path and that's why we need to do the ugly `File.expand_path('../../lib', __FILE__)` thing. Even if Puck were to add `lib` to the load path you would still need that code to make the files in `bin` runnable when unpacked.

This would mean that you instead would have to add more code to make sure that it didn't add to the load path when running from inside the jar – because if it did it would add the bad path and you would have the same problem.

You could do as you have done and catch `LoadError`, add to the load path and try again, but that's kind of what I mean with having to add more code to make sure that it worked. Solving the problem with exceptions also adds to the already slow startup time (try running JRuby with `-Xlog.exceptions=true` sometime and think about what all that makes to the startup time), and making JRuby look through the files in the jar twice for the file you want to load makes it even worse.

It's not a bad suggestion, but it's one that would go against my idea of how I want Puck to work.

> Question: Maybe it would be better to make this a configuration option?

For the same reasons as above I would prefer not making things work differently when running from inside the jar, even if it were a configuration option.

Having shot down your suggestions I'm going to go one step further and blame the problem on someone else: I think this is a bug in JRuby. Clearly it shouldn't add `C:/` after `classpath:`. It makes absolutely no sense for it to do that (the same goes for the `/` on *nix, but it's more subtle there).

Finally, let me switch to good cop: this of course needs to be fixed. Even if it's a bug in JRuby it will most likely not be fixed in 1.7.x because the guys are busy with 9K, and even with a fix in 9K there's a while before 9K will be ready for production for a while, so we need a workaround.

I don't have easy access to a Windows machine, unfortunately, so testing this might get time consuming, I might call on you to do some of it for me. I will have a look in JRuby and see what's going on there and if there's anything obvious that can be done either in Puck or as a patch to JRuby.

In the meantime I suggest using this workaround, it's the least obtrusive I can come up with at the moment, and it should work both unpacked and packed:

```ruby
$LOAD_PATH.unshift(File.expand_path('../../lib', __FILE__).sub(/^(?<=classpath:)C:\//, ''))
```

Maybe you've already come up with something similar.

I'm really sorry to not have a quick solution for you, but if there were a quick and easy one you would probably have found it yourself.

And again: thank you so much for the detailed bug report.

**Comment by jmcaffee** [comment]
This seems to do the job:

``` ruby
$LOAD_PATH.unshift(File.expand_path("../../lib", __FILE__).sub(/^classpath:(C:\/)/, 'classpath:'))
```


I couldn't get your version of regex to exclude `classpath:` on the substitution so I went with the brute force approach.

This change works when running packed and unpacked, thanks!

Let me know when/if you have something to test in win7 and I'll see what I can do.

Thanks again for looking at this.

**Comment by iconara** [comment]
Sorry, the regex should have been `/(?<=^classpath:)C:\//` (the `^` should have been inside the lookbehind).

**Comment by iconara** [comment]
@jmcaffee could you try out the code in #12 in Windows? I might have found a workaround. Turns out that `File.exist?` wants a "classpath:/"-prefixed path, but `load` happily takes a relative path. When the bin file is loaded using a relative path, `File.expand_path('../../lib', __FILE__)` returns another kind of path which should contain "C:/" in the right place. The path looks like "C:/path/to/the.jar!/META-INF/app.home/lib".

Now if I can just figure out how to report this as a bug to JRuby... I've found it hard to replicate it outside of Puck, and it seems to depend on the exact chain of `load`, `File.expand_path` and so on.

**Comment by jmcaffee** [comment]
Looks like your fix works...

`bin/mytestapp` header:

``` ruby
  $LOAD_PATH.unshift(File.expand_path("../../lib", __FILE__))
  puts 'LOAD_PATH:'
  $LOAD_PATH.each do |p|
    puts "  #{p}"
  end
  require 'mytestapp'

```


Linux Output:

    LOAD_PATH:
      file:/home/jeff/projects/ruby/mytestapp/build/mytestapp.jar!/META-INF/app.home/lib
      file:/home/jeff/projects/ruby/mytestapp/build/mytestapp.jar!/META-INF/jruby.home/lib/ruby/1.9/site_ruby
      file:/home/jeff/projects/ruby/mytestapp/build/mytestapp.jar!/META-INF/jruby.home/lib/ruby/shared
      file:/home/jeff/projects/ruby/mytestapp/build/mytestapp.jar!/META-INF/jruby.home/lib/ruby/1.9
      classpath:META-INF/gem.home/rake-10.1.0/lib
      classpath:META-INF/gem.home/builder-3.2.2/lib
      ...

Windows Output:

    LOAD_PATH:
      file:C:/Apps/MyTestApp/mytestapp.jar!/META-INF/app.home/lib
      file:/C:/Apps/MyTestApp/mytestapp.jar!/META-INF/jruby.home/lib/ruby/1.9/site_ruby
      file:/C:/Apps/MyTestApp/mytestapp.jar!/META-INF/jruby.home/lib/ruby/shared
      file:/C:/Apps/MyTestApp/mytestapp.jar!/META-INF/jruby.home/lib/ruby/1.9
      classpath:META-INF/gem.home/rake-10.1.0/lib
      classpath:META-INF/gem.home/builder-3.2.2/lib
      ...

**Comment by iconara** [comment]
That's great. I'll merge that into master and release a new gem.
